name: CMake Windows MSYS2

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch: [i686, x86_64]

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup MSYS2
      # You may pin to the exact commit or the version.
      # uses: msys2/setup-msys2@85b07cd9f310452566be859db1426bc664d08e9b
      uses: msys2/setup-msys2@v2
      with:
        # Update MSYS2 installation through pacman
        update: true
        msystem: ${{ matrix.arch == 'i686' && 'MINGW32' || 'MINGW64' }}
        # Install packages after installation through pacman
        install: mingw-w64-${{ matrix.arch }}-toolchain mingw-w64-${{ matrix.arch }}-cmake

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      shell: msys2 {0}
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: msys2 {0}
      working-directory: ${{runner.workspace}}/build
      # Note the current convention is to use the -S and -B options here to specify source 
      # and build directories, but this is only available with CMake 3.13 and higher.  
      # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_GENERATOR="MinGW Makefiles"

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: msys2 {0}
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: msys2 {0}
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --output-on-failure -C $BUILD_TYPE
